/**
 * AI Insight Engine (Premium) — deterministic rules engine.
 *
 * No LLM key is configured in this environment, so insights are generated by
 * pure rules over readings / till_entries / stock_movements. If an LLM key is
 * ever added (OPENAI_API_KEY / ANTHROPIC_API_KEY), a future pass could use it
 * to rewrite the `body` text in a friendlier voice — the underlying facts and
 * thresholds here should stay the source of truth either way.
 *
 * Everything here is a pure function — no Supabase calls — so it works
 * offline against whatever's already cached locally, and degrades cleanly
 * (returns fewer insights, never throws) when data is sparse.
 */
import { calcDailyConsumption, calcDaysOfCover, calcOrderFlag } from "./coverage";
import { calcGpPercent, calcCostPerMeasure, calcProductGpPercent } from "./calculations";

export type InsightType =
  | "variance_trend"
  | "over_pouring"
  | "days_of_cover"
  | "reorder_nudge"
  | "gp_drift"
  | "general";

export type InsightSeverity = "info" | "warning" | "critical";

export interface GeneratedInsight {
  type: InsightType;
  title: string;
  body: string;
  severity: InsightSeverity;
  data?: Record<string, unknown>;
}

export interface InsightProduct {
  id: string;
  name: string;
  size_ml: number | null;
  cost_price: number | null;
  pour_price: number | null;
  measure_ml: number | null;
  unit: "weigh" | "count";
}

export interface InsightReadingPoint {
  ml_remaining: number;
  reading_at: string;
}

export interface InsightTillEntry {
  product_id: string;
  measures_sold: number;
  period_start: string;
  period_end: string;
}

export interface InsightEngineInput {
  products: InsightProduct[];
  readingsByProduct: Map<string, InsightReadingPoint[]>;
  tillEntries: InsightTillEntry[];
  orderCycleDays: number;
  defaultMeasureMl: number;
}

const round1 = (n: number) => Math.round(n * 10) / 10;

/**
 * 1. Days-of-cover warnings + reorder nudges — reuses the same coverage math
 *    as the Reports "days of cover" feature so the numbers always agree.
 */
function daysOfCoverInsights(input: InsightEngineInput): GeneratedInsight[] {
  const out: GeneratedInsight[] = [];
  for (const p of input.products) {
    const readings = input.readingsByProduct.get(p.id) ?? [];
    if (readings.length < 2) continue;
    const sorted = [...readings].sort(
      (a, b) => new Date(b.reading_at).getTime() - new Date(a.reading_at).getTime(),
    );
    const current = sorted[0].ml_remaining;
    const avgMlPerDay = calcDailyConsumption(readings);
    if (avgMlPerDay <= 0) continue;
    const daysOfCover = calcDaysOfCover(current, avgMlPerDay);
    const flagged = calcOrderFlag(daysOfCover, input.orderCycleDays);
    if (!flagged || !isFinite(daysOfCover)) continue;

    const critical = daysOfCover < input.orderCycleDays * 0.5;
    out.push({
      type: "reorder_nudge",
      title: `${p.name} — order soon`,
      body: `At the current pour rate, ${p.name} has about ${Math.max(0, Math.round(daysOfCover))} day${Math.round(daysOfCover) === 1 ? "" : "s"} of cover left, but your order cycle is ${input.orderCycleDays} days. Put it on the next order to avoid running dry.`,
      severity: critical ? "critical" : "warning",
      data: { productId: p.id, daysOfCover: round1(daysOfCover), orderCycleDays: input.orderCycleDays },
    });
  }
  return out;
}

/**
 * 2. Over-pouring — compares weight-derived ml consumed per measure sold
 *    (from the till) against the product's stated measure size. Consistently
 *    pouring >15% over the stated measure is flagged.
 */
function overPouringInsights(input: InsightEngineInput): GeneratedInsight[] {
  const out: GeneratedInsight[] = [];
  const entriesByProduct = new Map<string, InsightTillEntry[]>();
  for (const e of input.tillEntries) {
    if (!entriesByProduct.has(e.product_id)) entriesByProduct.set(e.product_id, []);
    entriesByProduct.get(e.product_id)!.push(e);
  }

  for (const p of input.products) {
    if (p.unit !== "weigh") continue;
    const measureMl = p.measure_ml ?? input.defaultMeasureMl;
    const entries = entriesByProduct.get(p.id) ?? [];
    if (entries.length === 0) continue;

    const readings = input.readingsByProduct.get(p.id) ?? [];
    if (readings.length < 2) continue;
    const sorted = [...readings].sort(
      (a, b) => new Date(a.reading_at).getTime() - new Date(b.reading_at).getTime(),
    );

    let totalConsumedMl = 0;
    let totalMeasuresSold = 0;
    for (const entry of entries) {
      const start = sorted.find(
        (r) => new Date(r.reading_at).getTime() <= new Date(entry.period_start).getTime(),
      );
      const startReading = sorted
        .filter((r) => new Date(r.reading_at).getTime() <= new Date(entry.period_end).getTime())[0];
      const endReading = [...sorted]
        .reverse()
        .find((r) => new Date(r.reading_at).getTime() <= new Date(entry.period_end).getTime());
      if (!startReading || !endReading || startReading === endReading) continue;
      const consumed = startReading.ml_remaining - endReading.ml_remaining;
      if (consumed <= 0 || entry.measures_sold <= 0) continue;
      totalConsumedMl += consumed;
      totalMeasuresSold += entry.measures_sold;
      void start;
    }

    if (totalMeasuresSold < 5 || totalConsumedMl <= 0) continue;
    const actualMlPerMeasure = totalConsumedMl / totalMeasuresSold;
    const overPourPct = ((actualMlPerMeasure - measureMl) / measureMl) * 100;

    if (overPourPct > 15) {
      out.push({
        type: "over_pouring",
        title: `${p.name} — possible over-pouring`,
        body: `Weight suggests ${round1(actualMlPerMeasure)}ml is going into each measure of ${p.name}, against a stated ${measureMl}ml — that's ${Math.round(overPourPct)}% over. Worth a quick check on pour discipline or optics calibration.`,
        severity: overPourPct > 30 ? "critical" : "warning",
        data: { productId: p.id, actualMlPerMeasure: round1(actualMlPerMeasure), statedMeasureMl: measureMl, overPourPct: Math.round(overPourPct) },
      });
    }
  }
  return out;
}

/**
 * 3. Variance trend — weight-derived measures sold vs till-reported measures
 *    sold over the same window. A gap that keeps widening points to stock
 *    loss (spillage, over-pouring, or under-ringing at the till).
 */
function varianceTrendInsights(input: InsightEngineInput): GeneratedInsight[] {
  const out: GeneratedInsight[] = [];
  const entriesByProduct = new Map<string, InsightTillEntry[]>();
  for (const e of input.tillEntries) {
    if (!entriesByProduct.has(e.product_id)) entriesByProduct.set(e.product_id, []);
    entriesByProduct.get(e.product_id)!.push(e);
  }

  for (const p of input.products) {
    if (p.unit !== "weigh" || !p.size_ml) continue;
    const measureMl = p.measure_ml ?? input.defaultMeasureMl;
    const entries = (entriesByProduct.get(p.id) ?? []).sort(
      (a, b) => new Date(a.period_start).getTime() - new Date(b.period_start).getTime(),
    );
    if (entries.length < 2) continue;

    const readings = input.readingsByProduct.get(p.id) ?? [];
    const sorted = [...readings].sort(
      (a, b) => new Date(a.reading_at).getTime() - new Date(b.reading_at).getTime(),
    );

    const gaps: number[] = [];
    for (const entry of entries) {
      const startReading = [...sorted]
        .reverse()
        .find((r) => new Date(r.reading_at).getTime() <= new Date(entry.period_start).getTime());
      const endReading = [...sorted]
        .reverse()
        .find((r) => new Date(r.reading_at).getTime() <= new Date(entry.period_end).getTime());
      if (!startReading || !endReading || startReading === endReading) continue;
      const consumedMl = startReading.ml_remaining - endReading.ml_remaining;
      if (consumedMl <= 0) continue;
      const weighMeasures = consumedMl / measureMl;
      const gapMeasures = weighMeasures - entry.measures_sold;
      const gapPct = entry.measures_sold > 0 ? (gapMeasures / entry.measures_sold) * 100 : 0;
      gaps.push(gapPct);
    }

    if (gaps.length < 2) continue;
    const avgGapPct = gaps.reduce((s, g) => s + g, 0) / gaps.length;
    const worsening = gaps[gaps.length - 1] > gaps[0] + 5;

    if (avgGapPct > 8 && worsening) {
      out.push({
        type: "variance_trend",
        title: `${p.name} — variance trending up`,
        body: `${p.name} is showing on average ${Math.round(avgGapPct)}% more stock used (by weight) than the till has recorded across recent checks, and the gap is widening. Worth a closer look at wastage, comps, or till entry.`,
        severity: avgGapPct > 20 ? "critical" : "warning",
        data: { productId: p.id, avgGapPct: Math.round(avgGapPct), samples: gaps.length },
      });
    }
  }
  return out;
}

/**
 * 4. GP drift — products sitting below the venue's healthy GP% band.
 */
function gpDriftInsights(input: InsightEngineInput): GeneratedInsight[] {
  const out: GeneratedInsight[] = [];
  for (const p of input.products) {
    const gpOrNull = calcProductGpPercent(p, input.defaultMeasureMl);
    if (gpOrNull === null) continue;
    const gp = gpOrNull;
    if (gp < 55) {
      out.push({
        type: "gp_drift",
        title: `${p.name} — GP% below target`,
        body: `${p.name} is running at ${gp.toFixed(0)}% GP, below the 60% healthy line. Either the pour price hasn't kept pace with cost, or the measure is bigger than priced for.`,
        severity: gp < 45 ? "critical" : "warning",
        data: { productId: p.id, gpPercent: round1(gp) },
      });
    }
  }
  return out;
}

/**
 * Entry point — runs every rule and returns a de-duplicated, capped set of
 * insights for the week. Never throws; returns [] on insufficient data so the
 * UI can show a calm "not enough data yet" state instead of an error.
 */
export function generateWeeklyInsights(input: InsightEngineInput): GeneratedInsight[] {
  try {
    const all = [
      ...varianceTrendInsights(input),
      ...overPouringInsights(input),
      ...daysOfCoverInsights(input),
      ...gpDriftInsights(input),
    ];
    // Critical first, then warning, then info; cap to keep the weekly digest scannable.
    const order: Record<InsightSeverity, number> = { critical: 0, warning: 1, info: 2 };
    all.sort((a, b) => order[a.severity] - order[b.severity]);
    return all.slice(0, 12);
  } catch {
    return [];
  }
}
